services:
  trino-coordinator:
    image: 'trinodb/trino:latest'
    hostname: trino-coordinator
    ports:
      - '8080:8080'
    volumes:
      - ./trino/etc:/etc/trinolJ/fp2U6vikzZHg3xmLjGGVhaw8mLoh6bHTOz4bt
